Fix the relay define's outbound_bindaddresses default value setting.
Apparently, we have no guarantee $outbound_bindaddresses's value is set *after*
$listen_addresses is, so (at least on my setup) it ends up being undef,
and then the template parsing fails:

err: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed
to parse template tor/torrc.relay.erb: undefined method `each' for :undef:Symbol
at /etc/puppet/modules/tor/manifests/daemon.pp:117

So, let's set $real_outbound_bindaddresses to $listen_addresses in the define
body, as needed.